include:
  - component: gitlab.com/wa-pipelines/nodejs/gitlab-ci-node@0.0.1
    inputs:
      image: "registry.hub.docker.com/library/node:20" # this is only an example
      lint-enabled: "true"

stages:
    - install
    - test
    - build
    - run
    
install_dependencies:
    stage: install
    script:
        - npm install
        
 test:
    stage: test
    script:
        - npm test
        
 build:
    stage: build
    script:
        - npm build
    only:
        - main
  
 run:
    stage: run
    script:
        - echo "run application"
        - node app.js
        