image: node:latest


stages: 
    - build
    - run
    - test
    

build:
    stage: build
    script:
        - npm install
    only:
        - main

run:
    stage: run
    script:
        - echo "run application"
        - node app.js 

test:
    stage: test
    script: npm test
        