stages: 
    - build
    - install
    - run
    - test
    

install_dependencies:
  stage: install
  image: node:14
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
    stage: build
    script:
        - npm install
    only:
        - main

run:
    stage: run
    script:
        - echo "run application"
        - node app.js & sleep 10

test:
    stage: test
    script: npm test
    dependencies:
    - install_dependencies
        