stages: 
  - install
  - build
  - run
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:14
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  image: node:14
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  only:
    - main

run:
  stage: run
  image: node:14
  script:
    - echo "run application"
    - npm start & sleep 10
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  image: node:14
  script:
    - npm start & sleep 5 # Start the server in the background
    - npm test
  dependencies:
    - install_dependencies
  cache:
    paths:
      - node_modules/
