image: node:latest


stages: 
    - install
    - build
    - run
    - test
    
install:
    stage: install
    script:
        - npm install

build:
    stage: build
    script:
        - npm build
    only:
        - main

run:
    stage: run
    script:
        - echo "run application"
        - node app.js & sleep 5

test:
    stage: test
    script: login.test.js
        